engines:
  eslint:
    enabled: true
    config:
      extensions:
        - .js
        - .vue
  duplication:
    enabled: true
    config:
      languages:
        - javascript
      extensions:
        - .jsi
        - .vue
ratings:
  paths:
    - "**.js"
    - "**.vue"
